### ISSUE TITLE
When using a custom layout, deletes certain directories that are not in exportsOverride

### ISSUE THREAD

**Issue by anselmbradford** [yatskevich/grunt-bower-task#159]
I'm using `"history.js": "~1.8.0"` in a project and have a custom layout function:

```
layout: function(type, component, source) {
  var lib = config.loc.lib;
  var dist = config.loc.dist + '/static/';
  var assetPath = component;
  if (type === 'img' || type === 'fonts') {
    assetPath = path.relative( lib , dist + type );
    grunt.log.writeln('Moving ./' + source + ' to ' + dist + type);
  }
  return assetPath;
}
```

`config.loc.lib` is `src/vendor` and `config.loc.dist` is `.`. 

So unless there is an img or fonts type found, the directory is copied in place. However, for `history.js` (and another one–`string_score`), unless these appear in `exportsOverrides` in `bower.json` they will throw an `ENOENT` error from https://github.com/yatskevich/grunt-bower-task/blob/devel/tasks/lib/asset_copier.js#L50 because the package's directory gets completely deleted during the deep copy. Passing in the preserve option `wrench.copyDirSyncRecursive(source, destination, {preserve:true});` appears to fix it. Note if wrench is updated that option is now `preserveFiles`.

**Comment by codewithtyler** [comment]
@anselmbradford we have since switched from wrench to fs-extra. After looking through their API I'm still not sure if fs-extra preserves the directory or not. However, seeing as this issue was created originally due to a package we no longer use I'm going to go ahead and close it. If after the next release you find that fs-extra doesn't preserve the directory feel free to reopen this issue and I'll look into seeing what we can do to fix it.
