### ISSUE TITLE
exportsOverride into lib folder directly

### ISSUE THREAD

**Issue by bpletzer** [yatskevich/grunt-bower-task#5]
Hi,

I'd like to export chosen files directly into ./lib/<package>/ folder.

With the options at the moment it does not seem possible

``` javascript
{
 "exportsOverride": {
    "somePackage": {
      "js": "dist/**"
    }
}
```

could be

``` javascript
{
 "exportsOverride": {
    "somePackage": ['dist/**']
}
```

Unfortunatelly I just cannot say main: ['dist/**'] in the package's component.json

Greetings
Benedikt

**Comment by bpletzer** [comment]
ok, found a way:

``` javascript
{
  "exportsOverride": {
    "somePackage": {
      "js/../": "dist/**"
    }
}
```

does the trick

even better... ...

``` javascript
{
  "exportsOverride": {
    "somePackage": {
      "": "dist/**"
    }
}
```

**Comment by yatskevich** [comment]
Additionally you can take a look at [`grunt-bower`](https://github.com/curist/grunt-bower) project.

**Comment by chadly** [comment]
I have a similar request, but the referenced config doesn't solve my issue.  Most of my bower dependencies are single-file scripts and I'd like to dump them into the root of the lib folder rather than into a package subfolder.

Here is what I have now:

``` javascript
{
    "exportsOverride": {
        "somePackage": {
            "": "someFile.js"
    }
}
```

This copies `someFile.js` to `lib/somePackage/someFile.js`.  I'd like an option to copy it to the root lib folder, `lib/someFile.js`.

I am thinking an option in the config, `packageSubfolders` which could be set to false to have it skip the "packageName" subfolder.

I've also looked at the [grunt-bower](https://github.com/curist/grunt-bower) project you referenced, but it doesn't seem to do what I want either.  A lot of the projects I use don't specify a component.json which makes the exportsOverride config needed.

**Comment by IvanRave** [comment]
Chadly, it's easy to use simple grunt-contrib-copy instead this library with exportsOverride and your needs
