### ISSUE TITLE
Removed packages keep getting copied

### ISSUE THREAD

**Issue by SBoudrias** [yatskevich/grunt-bower-task#6]
Hi, here's the workflow in steps:
1. Declare dependencies in `components.json`
2. Install them (eg `grunt bower`)
3. Remove dependencies from `components.json`
4. Re-install

At this point, previously installed modules will still be copied in the project folder. This seems to occur because the task use all folder in `components` and don't clear removed dependencies.

**Comment by Iristyle** [comment]
:+1: to fixing this issue.... it starts to cause issues in our Jenkins builds.  We're using Janky to build PRs, and sometimes new pull requests add / remove a Bower package.

This will typically cause the following build to fail (mostly when we're using `exportOverrides` due to the package having a bad `component.json`)

**Comment by yatskevich** [comment]
@SBoudrias, @Iristyle Could you please try to use `cleanup: true` in task config:

``` javascript
grunt.initConfig({
  bower: {
    install: {
      options: { 
         cleanup: true,      
       }
    }
  },
})
```

If it doesn't work for you, please let me know.

**Comment by Iristyle** [comment]
I think this works (and can work around other bower cache issues as well).  I'll let you know if we run into any issues with this, but it seems sufficient for us.
