### ISSUE TITLE
grunt exit prematurely after bower task

### ISSUE THREAD

**Issue by ekarlso** [yatskevich/grunt-bower-task#66]
Is it not possible to use bower in a series of tasks ? 

grunt.registerTask('build', ['useminPrepare', 'concat', 'uglify', 'cssmin', 'htmlmin', 'usemin', 'copy:prod'])

grunt.registerTask('default', ['clean', 'bower', 'build']);

But it exits after the bower task?

**Comment by fantactuka** [comment]
Can you show a Gruntfile bower task config? It's a multi-task, so I guess it should be something like `bower:install`, not just `bower`

**Comment by ekarlso** [comment]
https://github.com/ekarlso/opendaylight-ui/blob/master/Gruntfile.js

**Comment by ekarlso** [comment]
Any news on this?

**Comment by yatskevich** [comment]
@ekarlso I've created a [gist](https://gist.github.com/yatskevich/6400079) and it works fine.

Please, take a look at it. Does it reflect your use-case?

**Comment by andyli** [comment]
Same problem here. But @yatskevich 's gist works... :(
Must be some other issue, but I have no time to debug further atm...

**Comment by ekarlso** [comment]
kinda yeah. But I dunno what is wrong. Care to help ???

2013/8/31 Andy Li notifications@github.com

**Comment by danielepolencic** [comment]
Hello,

I'm having the exact same problem. I spent some time debugging the task and the issue is caused by the `copy` settings. Apparently, settings the latter to `false` makes grunt proceed to the next task.

**Comment by ljskernel** [comment]
I think this is quite probably the same issue as referenced [here](https://github.com/yatskevich/grunt-bower-task/issues/38), which occurs when a `.bashrc` file is present in your project.

@fantactuka's [comment](https://github.com/yatskevich/grunt-bower-task/issues/38#issuecomment-19131596) (which does exactly what @danielepolencic suggests - setting copy to false) provides a solution in that thread which fixed the issue for me:-

``` javascript
 grunt.initConfig({
    bower: {
      install: {
        options: {
          install: true,
          copy: false
        }
      }
    })
```

This causes bower to install files in the location your `.bowerrc` specifies rather than copying them to a specified directory, hence not requiring the copying.

**Comment by psysp** [comment]
Had the same issue. Adding the options helped. Should be definitely be part of the documentation.

**Comment by quentindemetz** [comment]
Same here
